### ISSUE TITLE
[Nice-to-have N6] Incorporate generative AI to assist during the preparation

### ISSUE THREAD

**Issue by brein62** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#103]
For example, users can seek help from ChatGPT, Copilot (or such other services) to seek explanation of code written by the other participant. Users can seek help from gen AI to solve the puzzle by providing prompts from within the interface.

**Comment by larrywang0701** [comment]
I'll do the frontend UI/UX (together with my N1 chatting feature) and backend integration for this nice-to-have, and @brein62 you can focus on backend communication with 3rd party AI service APIs.

**Comment by brein62** [comment]
> I'll do the frontend UI/UX (together with my N1 chatting feature) and backend integration for this nice-to-have, and @brein62 you can focus on backend communication with 3rd party AI service APIs.
> 
> Please refer to [#98 (comment)](https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g36/issues/98#issuecomment-2448602888) for more information

as mentioned, do not touch this feature, just work on what you have. your N1 will be quite a lot of effort and you've already done N4 so you're more than covered workload-wise
