### ISSUE TITLE
[BUG] If user zoomed in too much, the chatbox and chatbot icons will block the end session button.

### ISSUE THREAD

**Issue by tiongMax** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#126]
![image](https://github.com/user-attachments/assets/19abc269-2587-44b2-ab4b-ef203d132338)

![image](https://github.com/user-attachments/assets/64b406c2-e992-4785-8a23-610d74e030ee)

**Comment by brein62** [comment]
fixed by #127
