### ISSUE TITLE
User Registration Frontend

### ISSUE THREAD

**Issue by larrywang0701** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#2]
- Basic UI for user registration:
  - User name box
  - Email box
  - Password box
  - CAPTCHA and input box
  - Registration button
- When user clicks registration button, send registration request to the backend

**Comment by brein62** [comment]
@larrywang0701 the frontend is fully up, you may start working on the design of the pages if you haven't yet

**Comment by larrywang0701** [comment]
Closing this issue since pull request #33 has already been merged.
