### ISSUE TITLE
Collaboration Service #2 select random interview question for the collaboration 

### ISSUE THREAD

**Issue by zacwong2151** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#89]
after matching 2 users, need to select a random question from our question database that match the difficulty and topic(s). Bring that question information to the collaboration page

**Comment by brein62** [comment]
btw one issue is that we don't have one question for every topic so what happens if there are no suitable questions?

we may need to update the question service and the topics list to ensure there at least exists one question of the topic accordingly

**Comment by zacwong2151** [comment]
> btw one issue is that we don't have one question for every topic so what happens if there are no suitable questions?
> 
> we may need to update the question service and the topics list to ensure there at least exists one question of the topic accordingly

simplest solution is what u suggested ba, put in more questions for each topic. Can reduce the number of topics in the hard-coded list too
