### ISSUE TITLE
Collaboration Service #3 bring the name of the person that you matched with, into the collaboration page

### ISSUE THREAD

**Issue by zacwong2151** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#90]
as per title

**Comment by brein62** [comment]
collab service will listen to a topic (u can decide what to name it)
when matching service matches 2 users tgt, send a message to that topic, containing the information of the 2 users' id and room id
collab will receive the message and do whatever functions u need to do

when collab updates its list of users who are currently collaborating, it sends a message to the matching service containing info about the users who are currently collaborating

- jayee 2024

**Comment by zacwong2151** [comment]
need to have some sort of 'end session' button in collab-service. When user ends session, collab-service updates its list, and sends the list to matching-service
