### ISSUE TITLE
[Nice-to-Have N1] Chatting function in collaboration room

### ISSUE THREAD

**Issue by larrywang0701** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#98]
Implement a text chatting function in collaboration room so collaborators can chat during collaborating

**Comment by brein62** [comment]
@larrywang0701 if you have a plan for this, do tell me since i think i'll use your system for my N6 AI assistance one

**Comment by larrywang0701** [comment]
@brein62 I already started working on this, the majority work is frontend UI/UX, and for your question you might most be interested in the backend part of the chatting feature. For now it's simply few lines in collaboration service backend:
```
type ChatMessage = {
    userToken: string,
    message: string,
}
.........
          socket.on('send-chat-message', (chatMessage: ChatMessage) => {
                // when server receives a chat message from client, server will broadcast the chat message
                socket.broadcast.to(documentId).emit("receive-chat-message", chatMessage)
            })
```
I think it would be easy for you to use this to trigger a request to your N6 AI assistance then use websocket to send the result generated from AI APIs to the frontend

**Comment by brein62** [comment]
just work on your N1 feature, don't bother touching the N6 any further. this implementation is good enough as it is, thank you!

i'll need the full chat history as well since the AI model requires full chat history for context. if you could do a function that does that it would be great as well
